version: "3.3"

services:
  grafana:
    image: grafana/grafana:8.4.7
    container_name: grafana
    restart: unless-stopped
    user: '1000'
    ports:
      - "3000:3000" # expose for localhost
    volumes:
      - $HOME/docker/grafana/data:/var/lib/grafana # data path
      - $HOME/docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - $HOME/docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      # - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
        
