version: "3"

services: 
  cadvisor:
    container_name: cadvisor
    command: --raw_cgroup_prefix_whitelist=/docker/ 
    hostname: rpi-cadvisor
    image: evanofslack/cadvisor:latest
    ipc: shareable
    networks:
      - rpimonitor_default
    privileged: true
    security_opt:
      - label=disable
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    expose:
      - 9100
    hostname: rpi-exporter
    image: prom/node-exporter:latest
    networks:
      - rpimonitor_default
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:8.4.7
    networks:
      - rpimonitor_default
    container_name: grafana
    restart: unless-stopped
    user: '1000:1000'
    ports:
      - "3000:3000" 

    volumes:
      - grafana-db:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-conf:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning

  prometheus:
    hostname: rpi-prom
    image: prom/prometheus:latest
    networks:
      - rpimonitor_default
    container_name: prometheous
    restart: unless-stopped
    user: '1000:1000'
    ports:
      - "9090:9090"
    volumes:
      - $HOME/docker/prometheus/data:/prometheus
      - $HOME/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  loki:
      container_name: loki
      image: grafana/loki:latest
      networks:
        - rpimonitor_default
      restart: unless-stopped
      ports:
        - "127.0.0.1:3100:3100"
      volumes:
        - $HOME/docker/loki/config/loki-config.yml:/etc/loki/loki-config.yml
        - $HOME/docker/loki/data:/data/loki
      command: -config.file=/etc/loki/loki-config.yml

  influxdb:
    image: hypriot/rpi-influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - $HOME/docker/influxdb/data:/data

volumes:
  grafana-db:
    driver: local
  grafana-log:
    driver: local
  grafana-conf:
    driver: local

networks:
  rpimonitor_default:
    external: true
