global:
  scrape_interval: 30s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.33.1.98:9090'] 
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.33.1.98:9100'] 