global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090', 'cadvisor:8080', 'node-exporter:9100']

  - job_name: 'ohmgraphite'
    scrape_interval: 30s
    static_configs:
      - targets: ['10.33.1.101:4445']
