---
version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $HOME/docker/adguard/conf:/opt/adguardhome/conf
      - $HOME/docker/adguard/work:/opt/adguardhome/work
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp
      # HTTPS
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3001:3000/tcp
    restart: unless-stopped

