services:
  cloudflared:
    image: erisamoe/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARED_TOKEN}
    networks:
      - rpimonitor_default


networks:
  rpimonitor_default:
    external: true

